
name: 'dbt_project_sd'
version: '1.0.0'


profile: 'dbt_project_sd'


model-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"

models:
  "dbt_project_sd":
    silver_airbnb:
      +schema: 'silver_airbnb'
      +materialized: view
    gold_airbnb:
      +schema: 'gold_airbnb'
      +materialized: table
    platinum_airbnb:
      +schema: 'platinum_airbnb'
      +materialized: view
    
