
name: 'dbt_training_nov_2025'
version: '1.0.0'


profile: 'dbt_training_nov_2025'


model-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"

models:
  dbt_training_nov_2025:
    silver_airbnb:
      +schema: 'silver_airbnb'
      +materialized: view
    gold_airbnb:
      +schema: 'gold_airbnb'
      +materialized: table
    platinum_airbnb:
      +schema: 'platinum_airbnb'
      +materialized: view
    
