'dbt_project_sd':
  outputs:
    dev:
      account: FJVTCIY-NC47989
      database: DEV
      password: $HALEENdashora@448!se
      role: TRANSFORM
      schema: BRONZE_AIRBNB
      threads: 1
      type: snowflake
      user: SHALIN001
      warehouse: COMPUTE_WH
    uat:
      account: FJVTCIY-NC47989
      database: uat
      password: dbtPassword123
      role: TRANSFORM
      schema: BRONZE_AIRBNB
      threads: 1
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
  target: dev
